#!/bin/bash
#MISE description="Run Go/WASM bridge tests"
set -euo pipefail

"${MISE_PROJECT_ROOT}/mise-tasks/go-wasm/build-wasm-release"
cd "${MISE_PROJECT_ROOT}/crates/go-wasm/go"
go test -race -v ./...
