// Copyright 2026 Asim Ihsan
//
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

//! Generates obfuscated service static public key bytes for the core crate.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const KEY_FILE_ENV: &str = "SECURE_TUNNEL_SERVICE_STATIC_PUBLIC_KEY_FILE";
const OBFUSCATION_SEED_ENV: &str = "SECURE_TUNNEL_OBFUSCATION_SEED";

fn main() {
    println!("cargo:rerun-if-env-changed={KEY_FILE_ENV}");
    println!("cargo:rerun-if-env-changed={OBFUSCATION_SEED_ENV}");

    let public_key = read_service_key();
    let mut rng = XorShift64::new(seed(&public_key));
    let generated = render_obfuscated_key(&public_key, &mut rng);
    let Some(out_dir) = env::var_os("OUT_DIR") else {
        panic!("OUT_DIR must be set");
    };
    if let Err(error) = fs::write(
        PathBuf::from(out_dir).join("service_static_key_obf.rs"),
        generated,
    ) {
        panic!("write generated service static key module: {error}");
    }
}

fn read_service_key() -> [u8; 32] {
    let Some(path) = env::var_os(KEY_FILE_ENV) else {
        return [9_u8; 32];
    };
    println!("cargo:rerun-if-changed={}", Path::new(&path).display());
    let bytes = match fs::read(path) {
        Ok(bytes) => bytes,
        Err(error) => panic!("read service static public key file: {error}"),
    };
    assert!(
        bytes.len() == 32,
        "service static public key file must contain exactly 32 bytes"
    );
    let mut out = [0_u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn render_obfuscated_key(public_key: &[u8; 32], rng: &mut XorShift64) -> String {
    let permutation = permutation(rng);
    let mask = random_array(rng);
    let salt = rng.next_u8();
    let control = rng.next_u8();
    let never_match = control.wrapping_add(1);
    let decoy_a = random_array(rng);
    let decoy_b = random_array(rng);
    let mut encoded = [0_u8; 32];

    for i in 0..32 {
        let j = usize::from(permutation[i]);
        let index = small_index(i);
        let rot = u32::from((index.wrapping_add(salt)) & 7);
        encoded[i] = (public_key[j] ^ mask[i])
            .rotate_left(rot)
            .wrapping_add(index.wrapping_mul(29));
    }

    format!(
        r"// @generated by crates/core/build.rs
use std::hint::black_box;
use std::sync::atomic::{{AtomicU8, Ordering}};

static ENC: [AtomicU8; 32] = {enc};
static MASK: [AtomicU8; 32] = {mask};
static PERM: [AtomicU8; 32] = {perm};
static DECOY_A: [AtomicU8; 32] = {decoy_a};
static DECOY_B: [AtomicU8; 32] = {decoy_b};
static SALT: AtomicU8 = AtomicU8::new({salt});
static CONTROL: AtomicU8 = AtomicU8::new({control});
static NEVER_MATCH: AtomicU8 = AtomicU8::new({never_match});

#[inline(never)]
pub fn decode_service_static_public_key() -> [u8; 32] {{
    let salt = SALT.load(Ordering::Relaxed);
    let mut out = [0_u8; 32];
    let mut control = CONTROL.load(Ordering::Relaxed);
    for i in 0..32 {{
        let e = ENC[i].load(Ordering::Relaxed);
        let m = MASK[i].load(Ordering::Relaxed);
        let j = usize::from(PERM[i].load(Ordering::Relaxed) & 31);
        let rot = u32::from((u8::try_from(i).unwrap_or_default().wrapping_add(salt)) & 7);
        let decoded = e
            .wrapping_sub(u8::try_from(i).unwrap_or_default().wrapping_mul(29))
            .rotate_right(rot)
            ^ m;
        out[j] = decoded;
        control = control.rotate_left(1) ^ decoded ^ u8::try_from(i).unwrap_or_default();
        if noisy_branch(i, control) {{
            black_box(DECOY_A[i].load(Ordering::Relaxed));
        }} else {{
            black_box(DECOY_B[31 - i].load(Ordering::Relaxed));
        }}
    }}
    black_box(control);
    out
}}

#[inline(never)]
fn noisy_branch(index: usize, control: u8) -> bool {{
    let mixed = CONTROL
        .load(Ordering::Relaxed)
        .wrapping_mul(3)
        .wrapping_add(control ^ u8::try_from(index).unwrap_or_default());
    mixed.rotate_left(3) != NEVER_MATCH.load(Ordering::Relaxed)
}}
",
        enc = render_atomic_array(&encoded),
        mask = render_atomic_array(&mask),
        perm = render_atomic_array(&permutation),
        decoy_a = render_atomic_array(&decoy_a),
        decoy_b = render_atomic_array(&decoy_b),
        salt = salt,
        control = control,
        never_match = never_match,
    )
}

fn render_atomic_array(bytes: &[u8; 32]) -> String {
    let mut out = String::from("[");
    for (index, byte) in bytes.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str("AtomicU8::new(");
        out.push_str(&byte.to_string());
        out.push(')');
    }
    out.push(']');
    out
}

fn random_array(rng: &mut XorShift64) -> [u8; 32] {
    let mut out = [0_u8; 32];
    for byte in &mut out {
        *byte = rng.next_u8();
    }
    out
}

fn permutation(rng: &mut XorShift64) -> [u8; 32] {
    let mut out = [0_u8; 32];
    for (index, value) in out.iter_mut().enumerate() {
        *value = small_index(index);
    }
    for index in (1..32).rev() {
        let swap = usize::from(rng.next_u8()) % (index + 1);
        out.swap(index, swap);
    }
    out
}

fn seed(public_key: &[u8; 32]) -> u64 {
    if let Ok(seed) = env::var(OBFUSCATION_SEED_ENV)
        && let Ok(seed) = u64::from_str_radix(seed.trim_start_matches("0x"), 16)
    {
        return seed.max(1);
    }

    let nanos = match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_nanos(),
        Err(error) => panic!("system clock must be after unix epoch: {error}"),
    };
    let nanos = nanos.to_le_bytes();
    let lower = u64::from_le_bytes([
        nanos[0], nanos[1], nanos[2], nanos[3], nanos[4], nanos[5], nanos[6], nanos[7],
    ]);
    let upper = u64::from_le_bytes([
        nanos[8], nanos[9], nanos[10], nanos[11], nanos[12], nanos[13], nanos[14], nanos[15],
    ]);
    let mut value = lower ^ upper;
    for (index, byte) in public_key.iter().enumerate() {
        value ^= u64::from(*byte) << ((index % 8) * 8);
        value = value.rotate_left(7).wrapping_mul(0x9e37_79b9_7f4a_7c15);
    }
    value.max(1)
}

fn small_index(index: usize) -> u8 {
    match u8::try_from(index) {
        Ok(index) => index,
        Err(error) => panic!("small index must fit in u8: {error}"),
    }
}

struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    const fn next_u8(&mut self) -> u8 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 7;
        self.state ^= self.state << 17;
        self.state.to_le_bytes()[0]
    }
}
