#!/usr/bin/env bash
#MISE description="Run the default lint suite"
set -euo pipefail

mise run check-format
mise run rust:check-clippy
mise run shell:lint


mise run python:lint


mise run go:lint
mise run go-wasm:lint

