#!/usr/bin/env bash
#MISE description="Set up local developer tooling"
set -euo pipefail

if [[ "$OSTYPE" == "darwin"* ]]; then
    mise run mac-setup
fi

case "$(uname -s)" in
    Darwin | Linux)
        mise run swift:setup
        ;;
esac

mise run rust:ensure-components


mise run python:setup





mise run go-wasm:setup
